import { Card } from "@/components/ui/card";
import { ApprovalActions } from "@/features/messages/components/approval-actions";
import { DraftCard } from "@/features/messages/components/draft-card";
import { MessageHistoryTable } from "@/features/messages/components/message-history-table";
import { MessagesTabs } from "@/features/messages/components/messages-tabs";
import type { OutboundMessageWithRelations } from "@/features/messages/types/message-types";
import {
  MESSAGE_CHANNEL_LABELS,
  MESSAGE_STATUS_LABELS,
  MESSAGE_TYPE_LABELS,
} from "@/features/messages/types/message-types";
import { getCustomerDisplayName } from "@/features/customers/utils/normalize-customer-identity";

type MessagesPageProps = {
  messages: OutboundMessageWithRelations[];
  canManage: boolean;
  activeTab: "all" | "approved" | "failed";
};

export function MessagesPage({ messages, canManage, activeTab }: MessagesPageProps) {
  const filtered =
    activeTab === "approved"
      ? messages.filter((message) => message.status === "APPROVED")
      : activeTab === "failed"
        ? messages.filter((message) => message.status === "FAILED")
        : messages.filter((message) => message.status !== "DRAFT");

  return (
    <div className="mx-auto max-w-5xl space-y-6">
      <section>
        <h1 className="text-3xl font-semibold tracking-tight text-zinc-950 sm:text-4xl">
          Customer communications
        </h1>
        <p className="mt-2 max-w-2xl text-base leading-8 text-zinc-600">
          Review, approve, and manage customer communications generated by ZOL.
        </p>
      </section>

      <MessagesTabs activeHref={activeTab === "approved" ? "/messages?tab=approved" : activeTab === "failed" ? "/messages?tab=failed" : "/messages"} />

      {filtered.length === 0 ? (
        <Card className="p-10 text-center text-sm text-zinc-500">
          No communications in this view yet.
        </Card>
      ) : activeTab === "all" || activeTab === "failed" ? (
        <MessageHistoryTable messages={filtered} />
      ) : (
        <div className="space-y-4">
          {filtered.map((message) => (
            <Card key={message.id} className="p-6">
              <div className="flex flex-wrap items-start justify-between gap-3">
                <div>
                  <p className="text-sm font-medium text-zinc-500">
                    {message.customer
                      ? getCustomerDisplayName(message.customer)
                      : message.conversation?.customerName ?? message.recipient}
                  </p>
                  <p className="mt-2 text-sm font-semibold text-zinc-900">
                    {MESSAGE_TYPE_LABELS[message.type]} · {MESSAGE_CHANNEL_LABELS[message.channel]}
                  </p>
                </div>
                <p className="text-xs text-zinc-500">{MESSAGE_STATUS_LABELS[message.status]}</p>
              </div>
              <p className="mt-4 text-sm leading-7 text-zinc-600">{message.content}</p>
              {canManage && message.status === "APPROVED" ? (
                <div className="mt-6">
                  <ApprovalActions messageId={message.id} mode="approved" />
                </div>
              ) : null}
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
